version: '3'
services:
  certbot:
    build: certbot-img/.  # Build custom certbot image, auto-renew
    container_name: certbot
    restart: unless-stopped
    volumes:
      - ./user-data/letsencrypt:/etc/letsencrypt # Certificates
      - ./certbot-www:/var/www/certbot           # For ACME challange
  nginx:
    image: nginx:1.21.4-alpine
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - certbot
    ports:
      - "80:80"
      - "443:443"
    volumes:
#      - ./user-data/nginx.conf:/etc/nginx/nginx.conf # Uncomment to use custom nginx.conf
      - ./user-data/conf.d:/etc/nginx/conf.d
      - ./user-data/letsencrypt:/etc/letsencrypt:ro         # Certificates from certbot
      - ./certbot-www:/var/www/certbot:ro  # ACME challange files when certbot renews
      - ./nginx-certbot.conf:/etc/nginx/nginx-certbot.conf  # .well-known path for certbot

